version: 0.2

env:
  variables:
    AWS_METADATA_ENDPOINT: "http://169.254.170.2:80$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI"

phases:
  install:
    commands:
      - echo 'deb http://us.archive.ubuntu.com/ubuntu vivid main universe' >> /etc/apt/sources.list
      - apt-get update
      - apt-get install jq
      - echo "here you are $AWS_CONTAINER_CREDENTIALS_RELATIVE_URI"
      - curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | jq 'to_entries | [ .[] | select(.key | (contains("Expiration") or contains("RoleArn"))  | not) ] |  map(if .key == "AccessKeyId" then . + {"key":"AWS_ACCESS_KEY_ID"} else . end) | map(if .key == "SecretAccessKey" then . + {"key":"AWS_SECRET_ACCESS_KEY"} else . end) | map(if .key == "Token" then . + {"key":"AWS_SESSION_TOKEN"} else . end) | map("export \(.key)=\(.value)") | .[]' -r > /tmp/aws_cred_export.txt
      - cat /tmp/aws_cred_export.txt
#      - curl http://169.254.170.2:80$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
  build:
    commands:
      - . /tmp/aws_cred_export.txt && docker run --rm -v $PWD:/data --workdir=/data hashicorp/terraform get terraform/project
      - . /tmp/aws_cred_export.txt && docker run --rm -v $PWD:/data --workdir=/data hashicorp/terraform plan --var-file terraform/envs/qa/qa.tfvars -state=terraform/envs/qa/terraform.tfstate terraform/project
