version: "3.0"

services:
  terraform:
    container_name: terraform-iac
    build: .
    image: terraform-iac
    working_dir: /app
    volumes:
      - $PWD:/app
    environment:
      - AWS_DEFAULT_REGION=eu-west-2
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_SECURITY_TOKEN=${AWS_SECURITY_TOKEN}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    tty: true